name: "Call example : Komodo Compose stack upsert (with manual delete)"

on:
  push:
    branches: [main]

  workflow_dispatch:
    # manual job destroy available
    inputs:
      action:
        type: choice
        options: [deploy, destroy]
        default: deploy

jobs:
  komodo:
    uses: blavogiez-org/komodo-upsert/.github/workflows/upsert-compose.yml@main
    with:
      compose_path: docker-compose.yml
      action: ${{ inputs.action || 'deploy' }}
    secrets: inherit
